### ISSUE TITLE
Dragging element

### ISSUE THREAD

**Issue by motss** [GoogleChromeLabs/pointer-tracker#1]
Can this be used to drag an element such as `table`? No luck in achieving that with native `PointerEvents` on touch devices as it loses pointer capture after a small distance.

Simple demo: https://cliff-store.glitch.me

**Comment by jakearchibald** [comment]
https://glitch.com/edit/#!/pointer-tracker-el-move?path=views/index.html - here you go. The main thing you were missing is `touch-action: none`.

**Comment by motss** [comment]
Thanks for the help.
