### ISSUE TITLE
triggerPointerEnd method is useful as public method

### ISSUE THREAD

**Issue by SachaMPS** [GoogleChromeLabs/pointer-tracker#3]
I forked this repo to make a very minor adjustment. Due to an iOS bug related to missing pointerUp events in some circumstances i needed to call triggerPointerEnd myself. The bug is also visible in this example: https://pinch-zoom-element.glitch.me/ 
If you move the picture to the very top on an iOS mobile device everything stops working as expected. It is fixable if you observe the pageY coordinates and call triggerPointerEnd like this (dummycode):

```
currentPointers.forEach((cp: Pointer) => {
            if (cp.pageY < 60 || cp.pageY > 600) {
                pointerTracker.triggerPointerEnd(cp, event);
                return;
            }
        });
```

**Comment by jakearchibald** [comment]
I think I've fixed this by hooking into pointer cancel. Please reopen with a reproduction if not.
