### ISSUE TITLE
setPointerCapture() disables click events in Chrome

### ISSUE THREAD

**Issue by MidnightDesign** [GoogleChromeLabs/pointer-tracker#4]
[This line](https://github.com/GoogleChromeLabs/pointer-tracker/blob/v2.0.3/lib/index.ts#L173) disables all click events inside the element, but only in Chrome.

I'm really sorry this is such a short ticket but I don't really have the time to create a reproducable case right now because my case is pretty involved, but I wanted to bring it up anyway. Please let me know if you need any additional information.

**Comment by jakearchibald** [comment]
Interesting! I think I currently assume that you're preventing default if you're returning true from the start callback, but I realise this isn't enforced.

A reduced test case would certainly help!

**Comment by MidnightDesign** [comment]
I actually do return `true` from the start callback. It's pretty much a copy of [the PinchZoom custom element from Squoosh](https://github.com/GoogleChromeLabs/squoosh/blob/master/src/components/Output/custom-els/PinchZoom/index.ts), but transformed into a React component.

Inside the pinchable element is an SVG (rendered by React) with `rect`s with React click handlers on them. Maybe it's a problem with the click event not being propagated to the React root?

(By the way, I'm a big fan of HTTP 203. Keep up the amazing work!)

**Comment by jakearchibald** [comment]
Are you calling `preventDefault` too?

**Comment by MidnightDesign** [comment]
Yes, [just like Squoosh](https://github.com/GoogleChromeLabs/squoosh/blob/master/src/components/Output/custom-els/PinchZoom/index.ts#L104).

**Comment by MidnightDesign** [comment]
If you're saying `preventDefault()` _shouldn't_ be there: I've tried to remove it and it doesn't make a difference. The clicks still aren't registered.

**Comment by jakearchibald** [comment]
I think the fix will be to change:

```js
this._element.setPointerCapture(event.pointerId);
```

To 

```js
event.target.setPointerCapture(event.pointerId);
```

Can you try that for me?

**Comment by MidnightDesign** [comment]
That works! Thank you so much. Should I open a PR?

**Comment by jakearchibald** [comment]
Yes please!

**Comment by MidnightDesign** [comment]
How should I handle the case where `event.target` is `null`? I would throw an error.

**Comment by jakearchibald** [comment]
Just to be safe:

```js
(event.target || this._element).setPointerCapture(event.pointerId);
```
